import { createHash } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import { env } from '@/lib/env';
import { logger } from '@/lib/logger';

/**
 * Object storage abstraction.
 *
 * The database stores keys and metadata only — never binaries. Moving from
 * local disk to Azure Blob + CDN in production is `STORAGE_DRIVER=azure`, with
 * no change to any call site.
 */
export interface StorageDriver {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  url(key: string): string;
}

/** Keys are opaque and generated by us; this rejects traversal regardless. */
function assertSafeKey(key: string): void {
  const clean = normalize(key);
  if (clean.startsWith('..') || clean.includes(`..${sep}`) || clean.startsWith(sep)) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

class LocalStorageDriver implements StorageDriver {
  readonly name = 'local';
  private readonly root = resolve(env.STORAGE_LOCAL_DIR);

  private pathFor(key: string): string {
    assertSafeKey(key);
    const full = resolve(join(this.root, key));
    // Defence in depth: the resolved path must stay inside the root.
    if (!full.startsWith(this.root + sep) && full !== this.root) {
      throw new Error(`Unsafe storage key: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  async delete(key: string): Promise<void> {
    await unlink(this.pathFor(key)).catch(() => undefined);
  }

  url(key: string): string {
    return `${env.STORAGE_PUBLIC_BASE_URL}/${key}`;
  }
}

/**
 * Azure Blob driver. Declared with the production call shape; it refuses
 * rather than pretending when @azure/storage-blob is not installed, so a
 * misconfigured deployment fails visibly at the first upload instead of
 * silently losing images.
 */
class AzureBlobStorageDriver implements StorageDriver {
  readonly name = 'azure';
  private container: unknown = null;

  private async client() {
    if (this.container) return this.container;
    try {
      const mod = (await import(
        /* webpackIgnore: true */ '@azure/storage-blob' as string
      )) as {
        BlobServiceClient: {
          fromConnectionString(cs: string): {
            getContainerClient(name: string): unknown;
          };
        };
      };
      const service = mod.BlobServiceClient.fromConnectionString(
        env.AZURE_STORAGE_CONNECTION_STRING!,
      );
      this.container = service.getContainerClient(env.AZURE_STORAGE_CONTAINER);
      return this.container;
    } catch {
      throw new Error(
        'STORAGE_DRIVER=azure requires the @azure/storage-blob package. ' +
          'Install it in the production image or set STORAGE_DRIVER=local.',
      );
    }
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertSafeKey(key);
    const container = (await this.client()) as {
      getBlockBlobClient(k: string): {
        uploadData(b: Buffer, o: unknown): Promise<unknown>;
      };
    };
    await container.getBlockBlobClient(key).uploadData(body, {
      blobHTTPHeaders: { blobContentType: contentType, blobCacheControl: 'public, max-age=31536000, immutable' },
    });
  }

  async get(key: string): Promise<Buffer> {
    const container = (await this.client()) as {
      getBlockBlobClient(k: string): { downloadToBuffer(): Promise<Buffer> };
    };
    return container.getBlockBlobClient(key).downloadToBuffer();
  }

  async delete(key: string): Promise<void> {
    const container = (await this.client()) as {
      getBlockBlobClient(k: string): { deleteIfExists(): Promise<unknown> };
    };
    await container.getBlockBlobClient(key).deleteIfExists();
  }

  url(key: string): string {
    const account = /AccountName=([^;]+)/.exec(env.AZURE_STORAGE_CONNECTION_STRING ?? '')?.[1];
    return account
      ? `https://${account}.blob.core.windows.net/${env.AZURE_STORAGE_CONTAINER}/${key}`
      : `${env.STORAGE_PUBLIC_BASE_URL}/${key}`;
  }
}

export const storage: StorageDriver =
  env.STORAGE_DRIVER === 'azure' ? new AzureBlobStorageDriver() : new LocalStorageDriver();

logger.info('storage driver selected', { driver: storage.name });

export function checksumOf(buffer: Buffer): string {
  return createHash('sha256').update(buffer).digest('hex');
}
