import { createHash } from 'node:crypto';
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join, normalize, resolve, sep } from 'node:path';
import type { ContainerClient } from '@azure/storage-blob';
import { env } from '@/lib/env';
import { logger } from '@/lib/logger';

/**
 * Object storage abstraction.
 *
 * The database stores keys and metadata only — never binaries. Moving from
 * local disk to Azure Blob + CDN in production is `STORAGE_DRIVER=azure`, with
 * no change to any call site.
 */
export interface StorageDriver {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  delete(key: string): Promise<void>;
  url(key: string): string;
}

/** Keys are opaque and generated by us; this rejects traversal regardless. */
function assertSafeKey(key: string): void {
  const clean = normalize(key);
  if (clean.startsWith('..') || clean.includes(`..${sep}`) || clean.startsWith(sep)) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

class LocalStorageDriver implements StorageDriver {
  readonly name = 'local';
  private readonly root = resolve(env.STORAGE_LOCAL_DIR);

  private pathFor(key: string): string {
    assertSafeKey(key);
    const full = resolve(join(this.root, key));
    // Defence in depth: the resolved path must stay inside the root.
    if (!full.startsWith(this.root + sep) && full !== this.root) {
      throw new Error(`Unsafe storage key: ${key}`);
    }
    return full;
  }

  async put(key: string, body: Buffer): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, body);
  }

  get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key));
  }

  async delete(key: string): Promise<void> {
    await unlink(this.pathFor(key)).catch(() => undefined);
  }

  url(key: string): string {
    return `${env.STORAGE_PUBLIC_BASE_URL}/${key}`;
  }
}

/**
 * Azure Blob driver.
 *
 * The container is created with public *blob* read access (never container
 * listing): uploaded images are business photos meant to be seen, and serving
 * them straight from Blob storage keeps image traffic off the app server.
 * Nothing private is ever written here. The SDK is loaded on first use so a
 * development server on the local driver never pays for it.
 */
class AzureBlobStorageDriver implements StorageDriver {
  readonly name = 'azure';
  private container: ContainerClient | null = null;

  private async client(): Promise<ContainerClient> {
    if (this.container) return this.container;
    const { BlobServiceClient } = await import('@azure/storage-blob');
    const service = BlobServiceClient.fromConnectionString(env.AZURE_STORAGE_CONNECTION_STRING!);
    this.container = service.getContainerClient(env.AZURE_STORAGE_CONTAINER);
    return this.container;
  }

  async put(key: string, body: Buffer, contentType: string): Promise<void> {
    assertSafeKey(key);
    const container = await this.client();
    await container.getBlockBlobClient(key).uploadData(body, {
      blobHTTPHeaders: {
        blobContentType: contentType,
        // Keys are content-addressed, so a URL never changes meaning.
        blobCacheControl: 'public, max-age=31536000, immutable',
      },
    });
  }

  async get(key: string): Promise<Buffer> {
    assertSafeKey(key);
    const container = await this.client();
    return container.getBlockBlobClient(key).downloadToBuffer();
  }

  async delete(key: string): Promise<void> {
    assertSafeKey(key);
    const container = await this.client();
    await container.getBlockBlobClient(key).deleteIfExists();
  }

  url(key: string): string {
    // An absolute STORAGE_PUBLIC_BASE_URL (a CDN in front of the container)
    // wins; otherwise the blob endpoint itself.
    if (/^https:\/\//.test(env.STORAGE_PUBLIC_BASE_URL)) {
      return `${env.STORAGE_PUBLIC_BASE_URL.replace(/\/$/, '')}/${key}`;
    }
    const account = /AccountName=([^;]+)/.exec(env.AZURE_STORAGE_CONNECTION_STRING ?? '')?.[1];
    return account
      ? `https://${account}.blob.core.windows.net/${env.AZURE_STORAGE_CONTAINER}/${key}`
      : `${env.STORAGE_PUBLIC_BASE_URL}/${key}`;
  }
}

export const storage: StorageDriver =
  env.STORAGE_DRIVER === 'azure' ? new AzureBlobStorageDriver() : new LocalStorageDriver();

logger.info('storage driver selected', { driver: storage.name });

export function checksumOf(buffer: Buffer): string {
  return createHash('sha256').update(buffer).digest('hex');
}
