import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import nextPlugin from '@next/eslint-plugin-next';

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'storage/**',
      'storage-test/**',
      'coverage/**',
      // Generated by Next on every build; not ours to lint.
      'next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    plugins: { '@next/next': nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      // The database layer legitimately passes JSON through as `object`.
      '@typescript-eslint/no-empty-object-type': 'off',
    },
  },
  {
    files: ['prisma/**/*.ts', 'tests/**/*.ts', 'src/jobs/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
);
