import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import QRCode from 'qrcode';
import { db } from '@/lib/db';
import { env } from '@/lib/env';
import { Panel } from '@/components/ui/Primitives';
import { DownloadQr } from '@/components/business/DownloadQr';

export const metadata: Metadata = {
  title: 'Code QR',
  robots: { index: false, follow: false },
};

export const revalidate = 3600;

/**
 * A printable QR code for a business.
 *
 * Generated on the server as SVG, so the client bundle carries no QR library
 * at all and the result scales to a shop window without pixelating. High error
 * correction, because this ends up on a sticker that gets scuffed.
 */
export default async function BusinessQrPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;

  const business = await db.business.findUnique({
    where: { slug },
    select: { name: true, slug: true, status: true, tagline: true },
  });
  if (!business || business.status !== 'ACTIVE') notFound();

  const url = `${env.APP_URL.replace(/\/$/, '')}/business/${business.slug}`;

  const svg = await QRCode.toString(url, {
    type: 'svg',
    errorCorrectionLevel: 'H',
    margin: 1,
    width: 420,
    color: { dark: '#0E3B66', light: '#F5F1E8' },
  });

  return (
    <div className="z-section">
      <div className="z-container z-qr">
        <Panel className="z-qr__card">
          <p className="z-eyebrow">Réservez en ligne</p>
          <h1>{business.name}</h1>
          {business.tagline ? <p className="z-qr__tagline">{business.tagline}</p> : null}

          <div
            className="z-qr__code"
            // Generated by the qrcode library from our own URL — no user input.
            dangerouslySetInnerHTML={{ __html: svg }}
          />

          <p className="z-qr__url">{url}</p>
          <p className="z-qr__brand">
            <strong>ZYNETNA</strong>
            <span>Barber &amp; Beauty · Tunisie</span>
          </p>
        </Panel>

        <div className="z-qr__aside">
          <h2 className="z-profile__h3">Votre code QR</h2>
          <p className="z-policy">
            Imprimez-le sur votre vitrine, votre carte de visite ou votre miroir. Vos clients
            scannent et réservent sans vous appeler.
          </p>
          <DownloadQr svg={svg} slug={business.slug} name={business.name} />
          <p className="z-help">
            Le code pointe vers <Link href={`/business/${business.slug}`}>votre page publique</Link>.
            Il reste valable tant que votre établissement est en ligne.
          </p>
        </div>
      </div>
    </div>
  );
}
